import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/app.css";
import Navbar from "@/components/layout/Navbar";
import { ReactNode } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-arcady-bg`}>
        {" "}
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
