const API_BASE_URL = 'http://localhost:5000/api';
const POKEMON_API_URL = `${API_BASE_URL}/pokemon`;
const POKEMON_API_ROUTE = '/pokemon';

const GET_POKEMON = `${POKEMON_API_URL}`;
const GET_POKEMON_BY_ID = `${POKEMON_API_URL}/{id}`;
const GET_POKEMON_POKEDEX = `${POKEMON_API_URL}/pokedex`;
const POST_POKEMON_TO_POKEDEX = `${POKEMON_API_URL}/{id}/pokedex`;
const DELETE_POKEMON_FROM_POKEDEX = `${POKEMON_API_URL}/{id}/pokedex`;

export {
  API_BASE_URL,
  POKEMON_API_URL,
  POKEMON_API_ROUTE,
  GET_POKEMON,
  GET_POKEMON_BY_ID,
  GET_POKEMON_POKEDEX,
  POST_POKEMON_TO_POKEDEX,
  DELETE_POKEMON_FROM_POKEDEX,
};